adjust the `upsertNode` function to update edges that are within groups
reaviz/reaflow pull request #38
Opened 2021-01-22 13:33 UTC by VHalushko

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: [#37]

## What is the new behavior?
Newly created edges from `upsertNode` will take properties from the original edge and will be inserted in the right place

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2021-01-22 13:50 UTC, amcdnl requested changes
Looks good but would you mind adding a few quick tests for this?

2021-01-22 15:00 UTC, VHalushko commented
> Looks good but would you mind adding a few quick tests for this?

Sure! Also seems like the RegEx for the `testMatch` could not find any test so I also updated it, can you check it if it's right now?

2021-01-22 15:41 UTC, amcdnl approved these changes

2021-01-22 15:41 UTC, merged

2021-01-25 13:11 UTC, amcdnl commented
Released in 2.6.4