Improve Linking Nodes documentation example + add extended helpers
reaviz/reaflow pull request #72
Opened 2021-02-25 10:16 UTC by Vadorequest

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: 
- https://github.com/reaviz/reaflow/issues/47
- https://github.com/reaviz/reaflow/issues/42

## What is the new behavior?

Documentation improved.

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

Fixes https://github.com/reaviz/reaflow/issues/42

2021-02-25 10:40 UTC, Vadorequest commented
@amcdnl Ready for review :)

2021-03-01 13:24 UTC, amcdnl requested changes

2021-03-01 13:24 UTC, amcdnl commented on docs/Advanced/ExtendedUtils.stories.mdx
> +<Meta title="Docs/Advanced/Extended utils" />
```suggestion
<Meta title="Docs/Advanced/Custom Utils" />
```

2021-03-01 13:24 UTC, amcdnl commented on docs/Advanced/Utils.stories.mdx
> +> There are advanced examples in [Extended utils](/?path=/story/docs-advanced-extended-utils--page) page.
```suggestion
> There are advanced examples in [Custom Utils](/?path=/story/docs-advanced-custom-utils--page) page.
```

2021-03-01 13:24 UTC, amcdnl commented
Just a name tweak other LGTM

2021-03-01 20:06 UTC, Vadorequest commented
Applied, I didn't know I could apply suggestion directly from github, it's handy!

I gues you can merge now :)

2021-03-04 14:24 UTC, merged