Add ELK documentation
reaviz/reaflow pull request #75
Opened 2021-02-26 09:58 UTC by Vadorequest

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: 
- https://github.com/reaviz/reaflow/issues/4

## What is the new behavior?

Better documentation regarding ELK ("getting started") and default Reaflow configuration

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

⚠️ Depends on https://github.com/reaviz/reaflow/pull/63

2021-02-26 10:03 UTC, Vadorequest commented
@amcdnl This PR is "ready" for a first review. I consider it to be a draft, still. I wouldn't be surprised if you'd change things around.

Needs #63 to be merged beforehand.
Shouldn't be merged quite yet.

2021-03-04 15:29 UTC, amcdnl requested changes

2021-03-04 15:29 UTC, amcdnl commented on docs/Advanced/ELK.stories.mdx
> +<Meta title="Docs/Advanced/Eclipse Layout Kernel" />
Let's move this under `Getting Started` as `Layout` and then go into the whole ELK thing.

2021-03-04 15:29 UTC, amcdnl commented on docs/Advanced/ELK.stories.mdx
> +Unfortunately, the ELK/ELKjs documentation isn't TypeScript-friendly, and you'll need to dig into the ELK documentation and issues if you're trying to change **how the graph's layout behaves**.
Avoid negative statements.

2021-03-04 15:29 UTC, amcdnl commented on docs/Advanced/ELK.stories.mdx
> +> From experience, changing ELK behavior is tough, because it is hard to comprehend what option(s) should be changed to achieve one's goal.
Avoid negative statements.

2021-03-04 15:29 UTC, amcdnl commented on docs/Advanced/ELK.stories.mdx
> +> From experience, changing ELK behavior is tough, because it is hard to comprehend what option(s) should be changed to achieve one's goal.
Avoid using "I"

2021-03-04 15:29 UTC, amcdnl commented on docs/Advanced/ELK.stories.mdx
> +- [ELKjs issues opened by Austin](https://github.com/kieler/elkjs/issues?q=is%3Aissue+sort%3Aupdated-desc+author%3Aamcdnl)
Call this out as "opened by reaflow team"

2021-03-04 15:29 UTC, amcdnl commented on docs/Advanced/ELK.stories.mdx
> +> TLDR; They're willing to implement the feature (AKA "Standalone Edge Routing"), but they're waiting for an open source contribution.
I would reword this

2021-04-01 12:15 UTC, closed without merging